[edm]
dataset = "qm9"
datadir = "external/e3_diffusion_for_molecules/qm9/temp"
batch_size = 4
num_workers = 0
remove_h = false
include_charges = true
conditioning = []
model = "egnn_dynamics"
probabilistic_model = "diffusion"
diffusion_steps = 100
diffusion_noise_schedule = "polynomial_2"
diffusion_noise_precision = 1e-5
diffusion_loss_type = "l2"
normalize_factors = [1, 4, 1]
n_layers = 2
inv_sublayers = 1
nf = 32
tanh = true
attention = true
norm_constant = 1.0
sin_embedding = false
normalization_factor = 1.0
aggregation_method = "sum"
condition_time = true
lr = 1e-4
force_download = false
exp_name = "edm_qm9_smoke"
no_wandb = true
online = false
wandb_usr = ""
save_model = false
generate_epochs = 1
test_epochs = 1
n_report_steps = 1
visualize_every_batch = 100000000
augment_noise = 0.0
data_augmentation = false
break_train_epoch = false
ode_regularization = 0.001
resume = ""
start_epoch = 0
ema_decay = 0.0
dp = false
clip_grad = false
trace = "hutch"
brute_force = false
actnorm = true
no_cuda = true

[scheduler]
enabled = false
num_bins = 8
alpha = 0.0
ema_beta = 0.95
baseline_mix_rho = 1.0
hardness_type = "coord_only"
